# Generated by Django 5.0.6 on 2024-06-17 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('transaction', '0001_initial'),
        ('zauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingmodel',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lendingmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.bookitem'),
        ),
        migrations.AddField(
            model_name='lendingmodel',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zauth.member'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.bookitem'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zauth.member'),
        ),
    ]
