# Generated by Django 5.0.6 on 2024-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingmodel',
            name='status',
            field=models.CharField(choices=[('LOANED', 'LOANED'), ('CANCELED', 'CANCELED'), ('CLOSED', 'CLOSED')], default='LOANED', max_length=10),
        ),
    ]
