# Generated by Django 5.0.6 on 2024-06-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='category',
        ),
    ]
