# Generated by Django 5.0.6 on 2024-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookitem_author_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='metadata information related to book item for future'),
        ),
    ]
