# Generated by Django 5.0.6 on 2024-06-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookitem_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='slug',
            field=models.UUIDField(db_index=True, default='2b12e82a-c77f-414d-bbca-a5ab0c68657b', unique=True),
            preserve_default=False,
        ),
    ]
