# Generated by Django 5.0.6 on 2024-06-23 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='slug',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
