# Generated by Django 5.0.6 on 2024-06-22 07:49

import zauth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zauth', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', zauth.models.ZUserManager()),
            ],
        ),
    ]
