# Generated by Django 5.0.6 on 2024-06-22 08:04

import zauth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zauth', '0004_alter_librarian_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='librarian',
            managers=[
                ('objects', zauth.models.LibrarianManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', zauth.models.MemberManager()),
            ],
        ),
    ]
